[package]
name = "metal-benches"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aruminium.workspace = true
objc2.workspace = true
objc2-metal.workspace = true
objc2-foundation.workspace = true

[[bin]]
name = "bench"
path = "bench.rs"

[[bin]]
name = "compare"
path = "compare.rs"
