[package]
name = "rane"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "rust apple neural engine"
repository = "https://github.com/cyberia-to/honeycrisp"
homepage = "https://github.com/cyberia-to/honeycrisp"
keywords = ["ane", "neural-engine", "apple-silicon", "gpu", "macos"]
categories = ["os::macos-apis", "hardware-support", "science"]
readme = "README.md"

[dependencies]
unimem.workspace = true
acpu.workspace = true

[lib]
name = "rane"
path = "src/lib.rs"

[[bin]]
name = "rane_probe"
path = "src/probe/main.rs"

[[example]]
name = "matmul"
path = "examples/matmul.rs"
